name: xAuth
author: xFlare
main: xFlare\xAuth\Loader
version: "1.0.0"
api: [1.8.0]
description: xAuth protects your server and adds authentication.
commands:
    login:
        description: Log into your account.
    register:
        description: Register your account.
    changepw:
        description: Change your password.
    unregister:
        description: Unregister your account.
   
    
